FROM debian:trixie-slim

ENV DEBIAN_FRONTEND=noninteractive
ENV TERM=xterm-256color

# ---- Base system ----
RUN apt-get update && apt-get install -y \
    curl \
    git \
    unzip \
    wget \
    build-essential \
    ca-certificates \
    python3 \
    python3-pip \
    python3-venv \
    && rm -rf /var/lib/apt/lists/*

# ---- Neovim ----
RUN curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz && \
		rm -rf /opt/nvim-linux-x86_64 && \
		tar -C /opt -xzf nvim-linux-x86_64.tar.gz
ENV PATH="$PATH:/opt/nvim-linux-x86_64/bin"
COPY ./nvim /root/.config/nvim

# ---- Python LSP ----
RUN pip install --break-system-packages pyright

CMD ["bash"]
