preload = /home/eskyl/images/wallpaper.jpg
wallpaper {
	monitor = DP-2
	path = /home/eskyl/images/wallpaper.jpg
	fit_mode = cover
}

wallpaper {
	monitor = HDMI-A-1
	path = /home/eskyl/images/wallpaper.jpg
	fit_mode = cover
}
splash = false
